### ISSUE TITLE
Cannot shrink the sidebar

### ISSUE THREAD

**Issue by Pastafarianist** [Thibaut/devdocs#265]
I expanded the sidebar by dragging its edge to the right, and now I cannot shrink it: every time I drag its edge to the left and release the mouse, it jumps back to where it started. Chrome 44.0.2403.157 (64-bit).

**Comment by Thibaut** [comment]
Does the sidebar resize while you drag? Does it jump back immediately when you release the mouse, or after you reload the page?

**Comment by Pastafarianist** [comment]
It does resize while I drag it, and it jumps back immediately as soon as I release the mouse.

**Comment by Thibaut** [comment]
What does `window.screenX` give you in the console?

**Comment by Thibaut** [comment]
I just deployed a change that may fix the issue.

**Comment by Pastafarianist** [comment]
> window.screenX
    < 1600

Also, every time I try to resize the sidebar, the console receives:

    Application Cache Checking event (index):1
    Application Cache NoUpdate event (index):1

**Comment by FallenMax** [comment]
I'm also having this problem and I found a workground: 
Delete this cookie `width=600` and refresh page, sidebar will shrink to default width. 

Just refrain from resizing it again, because that will set it back to 600px...

**Comment by Thibaut** [comment]
Which OS are you using?

**Comment by Pastafarianist** [comment]
Gentoo Linux.

**Comment by mishak87** [comment]
:+1: 600px Ubuntu 14.04

**Comment by ywg** [comment]
I have the same issue on Opera / Windows 10.
Any attemp to resize the sidebar will fail and the sidebar will always grow to a very large width on drop.

**Comment by Thibaut** [comment]
I just deployed a potential fix. Could one of you try to reproduce again? (reload twice to get the new version)

**Comment by ywg** [comment]
Yep, that fixed the issue for me (test done on Opera / Windows 7).
Thanks !

**Comment by mishak87** [comment]
Not for me size fixes at 600.

**Comment by Pastafarianist** [comment]
Works for me in Chrome under Kubuntu 15.10.

**Comment by Pastafarianist** [comment]
Still broken for me under Gentoo, but in a very weird way.

I *can* shrink the sidebar to the minimum width of 260px (according to the "Computed" tab under "Elements" in Chrome's developer console). When I start enlarging it by dragging it left-to-right, the sidebar follows smoothly the cursor. However, as soon as I release the mouse, it instantly jumps to a larger width, which is variable and depends on the width to which I enlarged it by dragging. Examples:

* 270 → 337
* 280 → 350
* 300 → 375
* 350 → 437
* 400 → 500

It looks like it always jumps by a factor of 5/4.

**Comment by Thibaut** [comment]
This bug is quite insane. The same code runs [`onDrag`](https://github.com/Thibaut/devdocs/blob/ddf87bb0b8749fd5366ce850009880d85b7749d1/assets/javascripts/views/layout/resizer.coffee#L41) and [`onDragEnd`](https://github.com/Thibaut/devdocs/blob/ddf87bb0b8749fd5366ce850009880d85b7749d1/assets/javascripts/views/layout/resizer.coffee#L49). Both read the cursor position from `event.pageX` but somehow `onDragEnd` ends up writing a different value, when it should always be the same as the last `onDrag` value (which is what I get on all the browsers I've tested). I even added a check that the `dragend` value is within 5px of the last `drag` value a [couple weeks ago](https://github.com/Thibaut/devdocs/commit/c2a20ef5863081aca00003bde4d50deca1a139a8).

@Pastafarianist could you check that there is "lastDragValue" in the script running DevDocs? (file like `/assets/application-[hash].js`) Maybe the cache didn't update or something.

Is your browser window aligned with the top left corner of your screen? full screen?

**Comment by Pastafarianist** [comment]
![image](https://cloud.githubusercontent.com/assets/1315874/11614732/1207af98-9c5c-11e5-8e2b-e05cafde50fc.png)

The Chrome window is typically maximized. I enabled full screen to take the screenshot.

I've also just checked that the bug is reproducible in incognito with all extensions disabled and with a non-maximized window.

**Comment by fvsch** [comment]
Firefox 43 on Windows: no resizing happens when dragging, and when releasing the sidebar is resized more or less accurately.

Firefox 45 (DevEdition) on Windows: no resizing happens when dragging, when releasing the sidebar is set at 600px (always), and can't be resized to a different value.

**Comment by Thibaut** [comment]
> no resizing happens when dragging

This is "normal". Firefox doesn't expose mouse coordinates on drag events. See https://bugzilla.mozilla.org/show_bug.cgi?id=505521 ¯\\\_(ツ)_/¯

> when releasing the sidebar is set at 600px (always), and can't be resized to a different value.

Unfortunately I can't replicate (I use BrowserStack) and ran out of ideas for how to fix this :/
Will try again later…

**Comment by chule143** [comment]
Hi guys in my case is something funny, I have two monitors: 1=1920x1080, 2=1360x768. When I resize the sidebar in the second monitor cannot stretch again:
![anim](https://cloud.githubusercontent.com/assets/1250071/12483692/d584ddee-c02c-11e5-8fcd-15ae88801bdf.gif)
But when I move the browser to the first monitor I can reduce the sidebar.

My specs: 
Chrome Version 47.0.2526.111
Linux Mint 17.2 XFCE 64-bit

**Comment by mishak87** [comment]
@chule143 You might have just found the root cause. I am working on dual/triple setups so long that I didn't realize that it could be the issue.

**Comment by Kaijiro** [comment]
I managed to reproduce this bug with your datas @chule143 :
  - Opened DevDocs on the first screen, resize sidebar.
  - Change DevDocs screen, try to resize sidebar => impossible.
  - Move DevDocs on the first screen again, and then, I can change sidebar size.

**Comment by chule143** [comment]
Using window.innerWidth instead window.screenX works for dual monitors (only for modern browsers  IE9+ xD) https://github.com/Thibaut/devdocs/pull/337

**Comment by Thibaut** [comment]
Thanks for the investigation. I'll take a look soon.

**Comment by Thibaut** [comment]
#337 didn't fix the issue but I believe a24a2ce1fe85f0938b05e951fe17ecc8bd2becb2 does. Let me know if not. Thanks all for helping debug this!

**Comment by Pastafarianist** [comment]
Works for me both on Kubuntu and on Gentoo. Thanks!
